version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: izmirim_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: izmirim_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: izmirim_api
    depends_on:
      - db
    ports:
      - "5000:8080" # Dışarıdan 5000 portu ile API'ye erişeceğiz
    environment:
      # ÖNEMLİ: Burada Host=db diyerek Docker içindeki veritabanı konteynerine bağlanıyoruz
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=izmirim_db;Username=admin;Password=securepassword123
      - ASPNETCORE_ENVIRONMENT=Development # Swagger arayüzünün görünmesi için

volumes:
  pgdata:
